(**************************************************************************)
(*                                                                        *)
(*                     The Sanskrit Heritage Platform                     *)
(*                                                                        *)
(*                              Gérard Huet                               *)
(*                                                                        *)
(* ©2021 Institut National de Recherche en Informatique et en Automatique *)
(**************************************************************************)
(*i module Inflected = struct i*)
(* Morphology : computation of inflected forms in [inflected_map decls].    *)
open Skt_morph
  
open Morphology
  
(* [inflected_map] *)
open Word
  
(* Holds the state vector : [(nouns,roots,preverbs,segmenting_mode)] where: *)
(* nouns is accumulator for the set of declined forms of substantives       *)
(* pronouns is accumulator for the set of declined forms of pronouns        *)
(* vocas is accumulator for the set of vocative forms of substantives       *)
(* roots is accumulator for the set of conjugated forms of roots            *)
(* preverbs is accumulator for the set of preverb sequences                 *)
(* [segmenting_mode] tells whether phantom phonemes are generated or not.   *)
(* This code serves 2 purposes: at building morphology time, it generates
all the forms to populate the morphology banks. It is also reused at execution
time, by Declension and Conjugation cgis. *)
(* Admits aa- as a preverb -- global set in [Verbs.compute_conjugs_stems] *)
let admits_aa = ref false
and admits_lopa = ref false
  
let morpho_gen = ref true
  
(* morphology generation time *)
(* Turn to [False] for cgi execution (fake conjugation and no phantoms) *)
(* The [inflected_map] lexicons of inflected forms: nouns, iics, etc are computed
   by [Make_nouns] and are dumped as persistent global databases nouns.rem etc.
   They are also used on the fly locally by [Declension] and [Conjugation]. *)
(* Unique naming mechanism *)
(* Currently used for participles, could be extended to other kridantas,
and even for taddhitaantas and compounds. Stems are addressed by their
morphology, the structure is initialised by the lexicalied ones. *)
let lexicalized_kridantas = ref (Deco.empty : Naming.deco_krid)
  
(* It will be set by [Make_roots.roots_to_conjugs] in the first pass of
grinding, and used for the [unique_kridantas] computation in the second. *)
let access_lexical_krid stem = Deco.assoc stem !lexicalized_kridantas
  
(* We look up the lexicalized kridantas register to see if entry is a krid. *)
(*i This test should be done before, in [Print_dict] that has the info ? i*)
let is_kridanta entry =
  try
    let (hom, stem) = Encode.decompose_str entry in
    let krids = access_lexical_krid stem in
    let _ = List.find (fun (_, h) -> h = hom) krids in true
  with | Not_found -> false
  
let unique_kridantas = ref Deco.empty
  
(* This structure holds the unique names to kridantas. It is initialized
to the lexicalized ones in [Make_roots.roots_to_conjugs], which completes it
with the kridantas generated by Parts. At the end of morphological generation 
its final value is stored in persistent [Data.unique_kridantas_file], and
transfered to [Data.public_unique_kridantas_file] read from module Naming. 
This allows the tag of kridantas to link to the lexicon entry in case it has
been lexicalized. This does not work for kridantas with preverbs, and at the
moment concerns only participles, not nouns of agent or action. *)
let access_krid stem = Deco.assoc stem !unique_kridantas
and register_krid stem vrp = (* used in [Parts.gen_stem] *)
  unique_kridantas := Deco.add1 !unique_kridantas stem vrp
  
(* Inflected forms of nouns pronouns numbers, *)
(* also used separately for ifc only nouns *)
let nouns = ref (Deco.empty : inflected_map)
and pronouns = ref (Deco.empty : inflected_map)
and (* demonstrative + personal pn *) vocas =
  ref (Deco.empty : inflected_map)
  
(* Add morphological feature i to form w relative to entry e, with d = diff e *)
let add_morph w d i = nouns := Lexmap.addl !nouns w ((d w), i)
and add_morphpro w d i = (* pronouns not usable as ifc *)
  pronouns := Lexmap.addl !pronouns w ((d w), i)
and
  (* Add vocative feature i to form w relative to entry e, with d = diff e *)
  add_voca w d i = vocas := Lexmap.addl !vocas w ((d w), i)
  
(* auxiliary verbs used in inchoative cvi construct and periphrastic perfect *)
let auxiliary = function | "bhuu#1" | "k.r#1" | "as#1" -> true | _ -> false
  
(* iic forms *)
let iics = ref (Deco.empty : inflected_map)
  
let add_morphi w d i = iics := Lexmap.addl !iics w ((d w), i)
  
(* avyaya iic forms *)
let avyayais = ref (Deco.empty : inflected_map)
  
(* avyaya ifc forms *)
let avyayafs = ref (Deco.empty : inflected_map)
  
let add_morphyai w d i = avyayais := Lexmap.addl !avyayais w ((d w), i)
  
let add_morphyaf w d i = avyayafs := Lexmap.addl !avyayafs w ((d w), i)
  
(* Used by [Nouns.fake_compute_decls] for declension of single entry *)
let nominal_databases () =
  ((!nouns), (!pronouns), (!vocas), (!iics), (!avyayafs))
and reset_nominal_databases () =
  (nouns := Deco.empty;
   pronouns := Deco.empty;
   vocas := Deco.empty;
   iics := Deco.empty;
   avyayafs := Deco.empty)
  
(* iiv forms *)
let iivs = ref (Deco.empty : inflected_map)
  
let add_morphvi w d i = iivs := Lexmap.addl !iivs w ((d w), i)
  
(* forms of auxiliary roots "k.r" "bhuu" and "as" *)
let auxi = ref (Deco.empty : inflected_map)
and (* red tinantas *) auxiinv = ref (Deco.empty : inflected_map)
  
(* mauve abs and inf *)
let add_morphauxi w d i =
  if Phonetics.phantomatic w
  then ()
  else auxi := Lexmap.addl !auxi w ((d w), i)
and add_morphauxiinv w d i =
  if Phonetics.phantomatic w
  then ()
  else auxiinv := Lexmap.addl !auxiinv w ((d w), i)
  
(* periphrastic perfect forms *)
let peri = ref (Deco.empty : inflected_map)
  
let add_morphperi w d i = peri := Lexmap.addl !peri w ((d w), i)
  
(* indeclinable forms - adverbs, conjonctions, particles *)
let indecls = ref (Deco.empty : inflected_map)
  
let add_morphind w d i = indecls := Lexmap.addl !indecls w ((d w), i)
  
(* indeclinable forms usable as ifc  *)
let indifcs = ref (Deco.empty : inflected_map)
  
let add_morphindifc w d i = indifcs := Lexmap.addl !indifcs w ((d w), i)
  
(* invocations are registered in invs *)
let invs = ref (Deco.empty : inflected_map)
  
let add_invoc w d i = invs := Lexmap.addl !invs w ((d w), i)
  
(* indeclinable verbal forms usable without preverbs: infinitives, abs-tvaa *)
let abstvaa = ref (Deco.empty : inflected_map)
  
let add_morphabstvaa w d i = abstvaa := Lexmap.addl !abstvaa w ((d w), i)
  
(* indeclinable verbal forms usable with preverbs: infinitives, abs-ya *)
let absya = ref (Deco.empty : inflected_map)
  
let add_morphabsya w d i aapv =
  (absya := Lexmap.addl !absya w ((d w), i);
   (* now we add fake absol forms with phantom phonemes *)
   if !morpho_gen && aapv
   then
     (match w with
      | 1 :: r -> (* aa-a gives *a *)
          let fake = (* *a *) (-3) :: r
          in absya := Lexmap.addl !absya fake ((d fake), i)
      | 2 :: r ->
          let fake = (* *A *) (-9) :: r
          in absya := Lexmap.addl !absya fake ((d fake), i)
      | 3 :: r ->
          let fake = (* *i *) (-4) :: r
          in absya := Lexmap.addl !absya fake ((d fake), i)
      | 4 :: r ->
          let fake = (* *I *) (-7) :: r
          in absya := Lexmap.addl !absya fake ((d fake), i)
      | 5 :: r ->
          let fake = (* *u *) (-5) :: r
          in absya := Lexmap.addl !absya fake ((d fake), i)
      | 6 :: r ->
          let fake = (* *U *) (-8) :: r
          in absya := Lexmap.addl !absya fake ((d fake), i)
      | 7 :: r ->
          let fake = (* *r *) (-6) :: r
          in absya := Lexmap.addl !absya fake ((d fake), i)
      | 23 :: r -> (* aa-ch gives *C *)
          let fake = (* *C *) 123 :: r
          in absya := Lexmap.addl !absya fake ((d fake), i)
      | _ -> ())
   else ())
  
(* root finite conjugated forms *)
let roots = ref (Deco.empty : inflected_map)
  
let add_morphc w d i aapv =
  (roots := Lexmap.addl !roots w ((d w), i);
   (* now we add fake conjugated forms with phantom phonemes *)
   if !morpho_gen && aapv
   then (* \Pan{6,1,95} *)
     (match w with
      | 1 :: r -> (* aa-a gives *a *)
          let fake = (* *a *) (-3) :: r
          in roots := Lexmap.addl !roots fake ((d fake), i)
      | 2 :: r ->
          let fake = (* *A *) (-9) :: r
          in roots := Lexmap.addl !roots fake ((d fake), i)
      | 3 :: r ->
          let fake = (* *i *) (-4) :: r
          in roots := Lexmap.addl !roots fake ((d fake), i)
      | 4 :: r ->
          let fake = (* *I *) (-7) :: r
          in roots := Lexmap.addl !roots fake ((d fake), i)
      | 5 :: r ->
          let fake = (* *u *) (-5) :: r
          in roots := Lexmap.addl !roots fake ((d fake), i)
      | 6 :: r ->
          let fake = (* *U *) (-8) :: r
          in roots := Lexmap.addl !roots fake ((d fake), i)
      | 7 :: r ->
          let fake = (* *r *) (-6) :: r
          in roots := Lexmap.addl !roots fake ((d fake), i)
      | 23 :: r -> (* aa-ch gives *C *)
          let fake = (* *C *) 123 :: r
          in roots := Lexmap.addl !roots fake ((d fake), i)
      | _ -> ())
   else ())
  
(* root finite forms starting with e or o *)
let lopas = ref (Deco.empty : inflected_map)
and lopaks = ref (Deco.empty : inflected_map)
  
(* Concerns \Pan{6,1,94} a,\=a (preverb) | e (root) -> e; same for o. *)
(* Ex: upelayati prelayati upo.sati pro.sati *)
let add_morphlopa w d i =
  match w with
  | 10 :: _ | 12 :: _ ->
      let amui = (-2) :: w
      in (* amuitic form *) lopas := Lexmap.addl !lopas amui ((d amui), i)
  | _ -> ()
  
(* New style of forms generators - stem argument generated as pseudo-entry *)
(* inflected forms of participles - and more generally kridantas *)
let parts = ref (Deco.empty : inflected_map)
  
let add_morphpa w stem i aapv =
  (parts := Lexmap.addl !parts w ((diff w stem), i);
   (* now we add fake participial forms with phantom phonemes *)
   if !morpho_gen && aapv
   then
     (match w with
      | 1 :: r -> (* aa-a gives *a *)
          let fake = (* *a *) (-3) :: r
          in parts := Lexmap.addl !parts fake ((diff fake stem), i)
      | 2 :: r ->
          let fake = (* *A *) (-9) :: r
          in parts := Lexmap.addl !parts fake ((diff fake stem), i)
      | 3 :: r ->
          let fake = (* *i *) (-4) :: r
          in parts := Lexmap.addl !parts fake ((diff fake stem), i)
      | 4 :: r ->
          let fake = (* *I *) (-7) :: r
          in parts := Lexmap.addl !parts fake ((diff fake stem), i)
      | 5 :: r ->
          let fake = (* *u *) (-5) :: r
          in parts := Lexmap.addl !parts fake ((diff fake stem), i)
      | 6 :: r ->
          let fake = (* *U *) (-8) :: r
          in parts := Lexmap.addl !parts fake ((diff fake stem), i)
      | 7 :: r -> (* aa-.r gives *r *)
          let fake = (* *r *) (-6) :: r
          in parts := Lexmap.addl !parts fake ((diff fake stem), i)
      | 23 :: r -> (* aa-ch gives *C *)
          let fake = (* *C *) 123 :: r
          in parts := Lexmap.addl !parts fake ((diff fake stem), i)
      | _ -> ())
   else ())
and add_morphlopak w stem i aapv =
  match w with
  | 10 :: _ | 12 :: _ ->
      let amui = (-2) :: w
      in
        (* amuitic form *)
        lopaks := Lexmap.addl !lopaks amui ((diff amui stem), i)
  | _ -> ()
  
(* participial vocatives *)
let partvocs = ref (Deco.empty : inflected_map)
  
let add_morphpav w stem i aapv =
  (partvocs := Lexmap.addl !partvocs w ((diff w stem), i);
   (* now we add fake participial forms with phantom phonemes *)
   if !morpho_gen && aapv
   then
     (match w with
      | 1 :: r -> (* aa-a gives *a *)
          let fake = (* *a *) (-3) :: r
          in partvocs := Lexmap.addl !partvocs fake ((diff fake stem), i)
      | 2 :: r ->
          let fake = (* *A *) (-9) :: r
          in partvocs := Lexmap.addl !partvocs fake ((diff fake stem), i)
      | 3 :: r ->
          let fake = (* *i *) (-4) :: r
          in partvocs := Lexmap.addl !partvocs fake ((diff fake stem), i)
      | 4 :: r ->
          let fake = (* *I *) (-7) :: r
          in partvocs := Lexmap.addl !partvocs fake ((diff fake stem), i)
      | 5 :: r ->
          let fake = (* *u *) (-5) :: r
          in partvocs := Lexmap.addl !partvocs fake ((diff fake stem), i)
      | 6 :: r ->
          let fake = (* *U *) (-8) :: r
          in partvocs := Lexmap.addl !partvocs fake ((diff fake stem), i)
      | 7 :: r -> (* aa-.r gives *r *)
          let fake = (* *r *) (-6) :: r
          in partvocs := Lexmap.addl !partvocs fake ((diff fake stem), i)
      | 23 :: r -> (* aa-ch gives *C *)
          let fake = (* *C *) 123 :: r
          in partvocs := Lexmap.addl !partvocs fake ((diff fake stem), i)
      | _ -> ())
   else ())
  
(* piic forms *)
let piics = ref (Deco.empty : inflected_map)
  
let add_morphpi w stem i aapv =
  (piics := Lexmap.addl !piics w ((diff w stem), i);
   (* now we add fake participial iic forms with phantom phonemes *)
   if !morpho_gen && aapv
   then
     (match w with
      | 1 :: r -> (* aa-a gives *a *)
          let fake = (* *a *) (-3) :: r
          in piics := Lexmap.addl !piics fake ((diff fake stem), i)
      | 2 :: r ->
          let fake = (* *A *) (-9) :: r
          in piics := Lexmap.addl !piics fake ((diff fake stem), i)
      | 3 :: r ->
          let fake = (* *i *) (-4) :: r
          in piics := Lexmap.addl !piics fake ((diff fake stem), i)
      | 4 :: r ->
          let fake = (* *I *) (-7) :: r
          in piics := Lexmap.addl !piics fake ((diff fake stem), i)
      | 5 :: r ->
          let fake = (* *u *) (-5) :: r
          in piics := Lexmap.addl !piics fake ((diff fake stem), i)
      | 6 :: r ->
          let fake = (* *U *) (-8) :: r
          in piics := Lexmap.addl !piics fake ((diff fake stem), i)
      | 7 :: r -> (* aa-.r gives *r *)
          let fake = (* *r *) (-6) :: r
          in piics := Lexmap.addl !piics fake ((diff fake stem), i)
      | 23 :: r -> (* aa-ch gives *C *)
          let fake = (* *C *) 123 :: r
          in piics := Lexmap.addl !piics fake ((diff fake stem), i)
      | _ -> ())
   else ())
  
(* kridantas of auxiliary roots k.r bhuu for cvi -ii compounds *)
let auxik = ref (Deco.empty : inflected_map)
  
let add_morphauxik w stem i =
  if Phonetics.phantomatic w
  then ()
  else auxik := Lexmap.addl !auxik w ((diff w stem), i)
  
let auxiick = ref (Deco.empty : inflected_map)
  
let add_morphauxiick w stem i =
  if Phonetics.phantomatic w
  then ()
  else auxiick := Lexmap.addl !auxiick w ((diff w stem), i)
  
(* Root infinitives in -tu with forms of kaama *)
let inftu = ref (Deco.empty : inflected_map)
and kama = ref (Deco.empty : inflected_map)
  
let add_morphinftu w d i = (* similar to [add_morphind] *)
  if Phonetics.phantomatic w
  then ()
  else inftu := Lexmap.addl !inftu w ((d w), i)
and add_morphkama w d i = (* similar to [add_morph] *)
  kama := Lexmap.addl !kama w ((d w), i)
  
(* Preverb sequences *)
let preverbs = ref (Deco.empty : word Deco.deco)
  
let add_morphp w i = preverbs := Deco.add !preverbs w i
  
(* Inflectional categories *)
type nominal =
  | Noun
  | (* lexicalized stem - noun, adjective or number *)
  Pron
  | (* lexicalized stem - pronoun *)
  Krid of verbal * string

(* kridantas of roots *)
type sup =
  (number * ((case * word) list))
  and (* stem *)
  (* nominal generators *)
  tin =
  (number * ((person * word) list))

(* root *)
(* verbal generators *)
type flexion =
  | Declined of nominal * gender * sup list
  | Conju of finite * tin list
  | Indecl of ind_kind * word
  | (* avyaya, particle, interjection, nota *)
  Indifc of ind_kind * word
  | (* indeclinable ifc *)
  Bare of nominal * word
  | (* Iic *)
  Avyayai of word
  | (* Iic of avyayiibhaava cpd *)
  Avyayaf of word
  | (* Ifc of avyayiibhaava cpd *)
  Cvi of word
  | (* -cvi suffixed stem (iiv) for inchoative compound verbs *)
  Preverb of word * word list
  | Invar of modal * word
  | (* infinitive abs-ya perpft *)
  Inftu of conjugation * Word.word
  | (* infinitive in -tu *)
  Absotvaa of conjugation * word

(* abs-tvaa *)
(* Now functions that populate the inflected forms treebanks from the lexemes *)
(* enter1: string -> flexion -> unit *)
let enter1 entry =
  let delta = Encode.diff_str entry
  and (* partial application for patching *) aapv = !admits_aa
  in
    (* for phantom forms generation *)
    function
    | Declined (Noun, g, lg) ->
        let (* nouns *) enterg (n, ln) =
          let entern (c, w) =
            let f = Noun_form (g, n, c)
            in
              if c = Voc
              then
                if !morpho_gen && (is_kridanta entry)
                then ()
                else (* f is in Kridv *) add_voca w delta f
              else (* non-generative Voca *)
                (add_morph w delta f;
                 (match entry with
                  | (* generative ifcs of infinitive bahus *)
                      "kaama" | (* volition : who wants to do *) "manas" ->
                      (* consideration : who thinks about doing *)
                      (* | "zakya" (* possibility : who is able to do *)  
                             (* not here since kridanta, cf [enter_form] *) *)
                      add_morphkama w delta f
                  | _ -> ()))
          in List.iter entern ln
        in List.iter enterg lg
    | Declined (Pron, g, lg) ->
        let (* pronouns *) enterg (n, ln) =
          let entern (c, w) =
            let f = Noun_form (g, n, c)
            in
              if c = Voc
              then add_voca w delta f
              else (* ? *) add_morphpro w delta f
          in List.iter entern ln
        in List.iter enterg lg
    | Conju (f, lv) ->
        let enterv (n, ln) =
          let entern (p, w) =
            let v = Verb_form (f, n, p)
            in
              (add_morphc w delta v aapv;
               (* Now we take care of \Pan{6,1,94} when not blocked by \Pan{6,1,89} *)
               (* ex: prejate + (Kazikaa) upelayati prelayati upo.sati pro.sati *)
               if !morpho_gen
               then
                 if (entry = "i") || (entry = "edh")
                 then ()
                 else (* \Pan{6,1,89} *) add_morphlopa w delta v
               else ();
               (* Now auxiliaries for verbal cvi compounds *)
               if auxiliary entry then add_morphauxi w delta v else ())
          in List.iter entern ln
        in List.iter enterv lv
    | Indecl (k, w) ->
        (match k with
         | Adv | Part | Conj | Default | Prep | Tas ->
             add_morphind w delta (Ind_form k)
         | Interj -> add_invoc w delta (Ind_form k)
         | Avya -> ()
         | (* marked as such in lexicon only if generative avyayiibhava *)
             Abs | Infl | Nota -> ())
    | (* no recording in morph tables *)
        (* Abs generated by absolutives of verbs, Infl by flexions of nouns, and
        our parser ignores the specific notations of Panini suutras *)
        Indifc (k, w) -> add_morphindifc w delta (Ind_form k)
    | Bare (Noun, w) | Bare (Pron, w) -> add_morphi w delta Bare_stem
    | Avyayai w -> add_morphyai w delta Avyayai_form
    | Avyayaf w -> add_morphyaf w delta Avyayaf_form
    | Cvi w -> add_morphvi w delta Gati
    | Invar (m, w) ->
        let (_, vi) = m
        and f = Ind_verb m
        in
          (match vi with
           | Infi ->
               ((* 2 cases: with and without preverbs - saves one phase *)
                add_morphabsya w delta f aapv;
                add_morphabstvaa w delta f;
                if auxiliary entry then add_morphauxiinv w delta f else ())
           | (*i was [add_morphc w delta f] but prevents being in same chunk as finite
          verb. PB : infinitives with preverbs are in diff category (Absoya);
          duplication could be avoided by using an extra specific phase. 
          Example of overgeneration: "paritraatum" with two "traatum". i*)
               Absoya -> (* abso in -ya *)
               (add_morphabsya w delta f aapv;
                (* abs-ya: pv or cvii (gati) mandatory *)
                if auxiliary entry then add_morphauxiinv w delta f else ())
           | Perpft -> add_morphperi w delta f)
    | (* NB Allows perpft of verbs with preverbs but overgenerates since
           it allows perpft followed by a non perfect form of auxiliary *)
        Inftu (m, w) ->
        let f = Ind_verb ((m, Infi)) in add_morphinftu w delta f
    | (* infinitive in -tu *) Absotvaa (c, w) ->
        let f = Abs_root c in add_morphabstvaa w delta f
    | (* abs-tvaa: no preverb *) Preverb (w, lw) -> add_morphp w lw
    | (* w is (normalised) sandhi of lw *) _ ->
        failwith "Unexpected arg to enter"
  
(* [enter_form: word -> flexion -> unit] *)
(* 1st argument is a stem generated by derivational morphology,
   it may have a homo index computed by [Parts.gen_stem]. *)
(* [enter_form] enters in the relevant data bank one of its inflected forms. *)
(* Special treatment to have kridanta forms for auxiliaries, since their 
   lexicalised action nouns are not recognized as generative, 
   and thus must be skipped to avoid overgeneration. *)
let enter_form stem =
  let aapv = !admits_aa
  in
    (* for phantom forms generation *)
    function
    | Declined ((Krid (v, root)), g, lg) ->
        let enterg (n, ln) =
          let entern (c, w) =
            let p = Part_form (v, g, n, c)
            in
              (* We lose the root, and v is used only in
         Constraints. Both can be recovered from stem using [unique_kridantas] *)
              if c = Voc
              then add_morphpav w stem p aapv
              else
                ((match v with
                  | (_, Action_noun) -> add_morphauxik w stem p
                  | (* cvi patch *) _ ->
                      (add_morphpa w stem p aapv;
                       if auxiliary root then add_morphauxik w stem p else ()));
                 if !morpho_gen
                 then
                   if (root = "i") || (root = "edh")
                   then ()
                   else (* \Pan{6,1,89} *) add_morphlopak w stem p aapv
                 else ())
          in List.iter entern ln
        in List.iter enterg lg
    | (*i TODO [; if v=Pfutp && root="zak" then imitate enter1] inftu-zakya i*)
        Bare ((Krid ((_, Action_noun), root)), w) ->
        add_morphauxiick w stem Bare_stem
    | (* cvi patch *) Bare ((Krid (_, root)), w) ->
        let f = Bare_stem
        in
          ((* losing verbal and root *)
           add_morphpi w stem f aapv;
           if auxiliary root then add_morphauxiick w stem f else ())
    | _ -> failwith "Unexpected arg to enter_form"
  
let enter entry = List.iter (enter1 entry)
and enter_forms w = List.iter (enter_form w)
  

