(**************************************************************************)
(*                                                                        *)
(*                     The Sanskrit Heritage Platform                     *)
(*                                                                        *)
(*                       Gérard Huet & Pawan Goyal                        *)
(*                                                                        *)
(* ©2022 Institut National de Recherche en Informatique et en Automatique *)
(**************************************************************************)

(* Generated by make version - see main Makefile *)
value version="3.51" and version_date="2023-11-27";
