(lang dune 3.20)

(name Heritage_Platform)

(generate_opam_files true)

(source
 (github username/reponame))

(authors "Roee Nizan <roeen30@gmail.com>")

(maintainers "Roee Nizan <roeen30@gmail.com>")

(license LICENSE)

(package
 (name Heritage_Platform)
 (synopsis "A short synopsis")
 (description "A longer description")
 (depends ocaml)
 (tags
  ("add topics" "to describe" your project)))


; See the complete stanza docs at https://dune.readthedocs.io/en/stable/reference/dune-project/index.html
